"""
Tax form generation service.
"""
from typing import Dict, Any, Optional
from datetime import datetime, date
from sqlalchemy.orm import Session
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import os

from app.db.models import TaxForm, TaxFormTypeEnum
from app.core.config import settings


class TaxFormGenerator:
    """Service for generating tax forms."""

    def __init__(self, db: Session):
        self.db = db
        self.output_dir = "./generated_forms"
        os.makedirs(self.output_dir, exist_ok=True)

    async def generate_1099_nec(
        self,
        creator_id: int,
        tax_year: int,
        payer_info: Dict[str, str],
        recipient_info: Dict[str, str],
        nonemployee_compensation: float
    ) -> TaxForm:
        """
        Generate Form 1099-NEC (Nonemployee Compensation).

        Args:
            creator_id: Creator ID
            tax_year: Tax year
            payer_info: Payer information dict
            recipient_info: Recipient information dict
            nonemployee_compensation: Amount paid

        Returns:
            TaxForm object
        """
        form_data = {
            "form_type": "1099-NEC",
            "tax_year": tax_year,
            "payer": {
                "name": payer_info.get("name"),
                "address": payer_info.get("address"),
                "city_state_zip": payer_info.get("city_state_zip"),
                "tin": payer_info.get("tin"),  # Tax ID Number
            },
            "recipient": {
                "name": recipient_info.get("name"),
                "address": recipient_info.get("address"),
                "city_state_zip": recipient_info.get("city_state_zip"),
                "tin": recipient_info.get("tin"),
            },
            "box_1_nonemployee_compensation": nonemployee_compensation,
            "box_4_federal_income_tax_withheld": 0.0,
            "box_5_state_tax_withheld": 0.0,
        }

        # Generate PDF
        filename = f"1099-NEC_{tax_year}_{creator_id}.pdf"
        filepath = os.path.join(self.output_dir, filename)

        self._generate_1099_nec_pdf(form_data, filepath)

        # Save to database
        tax_form = TaxForm(
            creator_id=creator_id,
            form_type=TaxFormTypeEnum.FORM_1099_NEC,
            tax_year=tax_year,
            form_data=form_data,
            pdf_url=filepath,
            pdf_filename=filename
        )

        self.db.add(tax_form)
        self.db.commit()
        self.db.refresh(tax_form)

        return tax_form

    def _generate_1099_nec_pdf(self, data: Dict, filepath: str):
        """Generate 1099-NEC PDF."""
        c = canvas.Canvas(filepath, pagesize=letter)
        width, height = letter

        # Title
        c.setFont("Helvetica-Bold", 14)
        c.drawString(1*inch, height - 1*inch, f"Form 1099-NEC ({data['tax_year']})")
        c.setFont("Helvetica", 10)
        c.drawString(1*inch, height - 1.3*inch, "Nonemployee Compensation")

        # Payer information
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1*inch, height - 2*inch, "PAYER'S name, street address, city, state, and ZIP code")
        c.setFont("Helvetica", 9)
        c.drawString(1*inch, height - 2.2*inch, data["payer"]["name"])
        c.drawString(1*inch, height - 2.4*inch, data["payer"]["address"])
        c.drawString(1*inch, height - 2.6*inch, data["payer"]["city_state_zip"])
        c.drawString(1*inch, height - 2.8*inch, f"TIN: {data['payer']['tin']}")

        # Recipient information
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1*inch, height - 3.5*inch, "RECIPIENT'S name, street address, city, state, and ZIP code")
        c.setFont("Helvetica", 9)
        c.drawString(1*inch, height - 3.7*inch, data["recipient"]["name"])
        c.drawString(1*inch, height - 3.9*inch, data["recipient"]["address"])
        c.drawString(1*inch, height - 4.1*inch, data["recipient"]["city_state_zip"])
        c.drawString(1*inch, height - 4.3*inch, f"TIN: {data['recipient']['tin']}")

        # Box 1 - Nonemployee compensation
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1*inch, height - 5*inch, "1. Nonemployee compensation")
        c.setFont("Helvetica", 12)
        c.drawString(1*inch, height - 5.3*inch, f"${data['box_1_nonemployee_compensation']:,.2f}")

        # Footer
        c.setFont("Helvetica", 8)
        c.drawString(1*inch, 0.5*inch, f"Generated by CreatorSync Tax Optimizer on {datetime.now().strftime('%Y-%m-%d')}")

        c.save()

    async def generate_schedule_c(
        self,
        creator_id: int,
        tax_year: int,
        business_info: Dict[str, Any],
        income_data: Dict[str, float],
        expense_data: Dict[str, float]
    ) -> TaxForm:
        """
        Generate Schedule C (Profit or Loss from Business).

        Args:
            creator_id: Creator ID
            tax_year: Tax year
            business_info: Business information
            income_data: Income breakdown
            expense_data: Expense breakdown

        Returns:
            TaxForm object
        """
        # Calculate totals
        gross_receipts = income_data.get("gross_receipts", 0.0)
        returns_and_allowances = income_data.get("returns_allowances", 0.0)
        gross_income = gross_receipts - returns_and_allowances

        # Part II - Expenses
        total_expenses = sum(expense_data.values())

        # Net profit
        net_profit = gross_income - total_expenses

        form_data = {
            "form_type": "Schedule C",
            "tax_year": tax_year,
            "business_info": business_info,
            "part_i_income": {
                "gross_receipts": gross_receipts,
                "returns_allowances": returns_and_allowances,
                "gross_income": gross_income,
            },
            "part_ii_expenses": expense_data,
            "total_expenses": total_expenses,
            "net_profit": net_profit,
            "at_risk": "all"  # All investment is at risk
        }

        # Generate PDF
        filename = f"Schedule_C_{tax_year}_{creator_id}.pdf"
        filepath = os.path.join(self.output_dir, filename)

        self._generate_schedule_c_pdf(form_data, filepath)

        # Save to database
        tax_form = TaxForm(
            creator_id=creator_id,
            form_type=TaxFormTypeEnum.SCHEDULE_C,
            tax_year=tax_year,
            form_data=form_data,
            pdf_url=filepath,
            pdf_filename=filename
        )

        self.db.add(tax_form)
        self.db.commit()
        self.db.refresh(tax_form)

        return tax_form

    def _generate_schedule_c_pdf(self, data: Dict, filepath: str):
        """Generate Schedule C PDF."""
        c = canvas.Canvas(filepath, pagesize=letter)
        width, height = letter

        # Title
        c.setFont("Helvetica-Bold", 14)
        c.drawString(1*inch, height - 1*inch, f"SCHEDULE C (Form 1040)")
        c.drawString(1*inch, height - 1.3*inch, f"Profit or Loss From Business")
        c.setFont("Helvetica", 10)
        c.drawString(1*inch, height - 1.6*inch, f"Tax Year {data['tax_year']}")

        # Business information
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1*inch, height - 2.2*inch, "A. Principal business or profession:")
        c.setFont("Helvetica", 9)
        c.drawString(1*inch, height - 2.4*inch, data["business_info"].get("description", "Content Creator"))

        # Part I - Income
        y_pos = height - 3*inch
        c.setFont("Helvetica-Bold", 11)
        c.drawString(1*inch, y_pos, "Part I - Income")

        c.setFont("Helvetica", 9)
        y_pos -= 0.3*inch
        c.drawString(1.2*inch, y_pos, f"1. Gross receipts or sales")
        c.drawString(5*inch, y_pos, f"${data['part_i_income']['gross_receipts']:,.2f}")

        y_pos -= 0.2*inch
        c.drawString(1.2*inch, y_pos, f"2. Returns and allowances")
        c.drawString(5*inch, y_pos, f"${data['part_i_income']['returns_allowances']:,.2f}")

        y_pos -= 0.2*inch
        c.setFont("Helvetica-Bold", 9)
        c.drawString(1.2*inch, y_pos, f"7. Gross income")
        c.drawString(5*inch, y_pos, f"${data['part_i_income']['gross_income']:,.2f}")

        # Part II - Expenses
        y_pos -= 0.5*inch
        c.setFont("Helvetica-Bold", 11)
        c.drawString(1*inch, y_pos, "Part II - Expenses")

        c.setFont("Helvetica", 9)
        for expense_name, amount in data["part_ii_expenses"].items():
            y_pos -= 0.2*inch
            c.drawString(1.2*inch, y_pos, f"{expense_name.replace('_', ' ').title()}")
            c.drawString(5*inch, y_pos, f"${amount:,.2f}")

        y_pos -= 0.3*inch
        c.setFont("Helvetica-Bold", 9)
        c.drawString(1.2*inch, y_pos, "Total expenses")
        c.drawString(5*inch, y_pos, f"${data['total_expenses']:,.2f}")

        # Net profit
        y_pos -= 0.5*inch
        c.setFont("Helvetica-Bold", 11)
        c.drawString(1*inch, y_pos, "Net Profit or (Loss)")
        c.drawString(5*inch, y_pos, f"${data['net_profit']:,.2f}")

        # Footer
        c.setFont("Helvetica", 8)
        c.drawString(1*inch, 0.5*inch, f"Generated by CreatorSync on {datetime.now().strftime('%Y-%m-%d')}")

        c.save()

    async def generate_w9(
        self,
        creator_id: int,
        taxpayer_info: Dict[str, str]
    ) -> TaxForm:
        """
        Generate Form W-9 (Request for Taxpayer ID).

        Args:
            creator_id: Creator ID
            taxpayer_info: Taxpayer information

        Returns:
            TaxForm object
        """
        form_data = {
            "form_type": "W-9",
            "name": taxpayer_info.get("name"),
            "business_name": taxpayer_info.get("business_name"),
            "tax_classification": taxpayer_info.get("classification", "Individual/sole proprietor"),
            "address": taxpayer_info.get("address"),
            "city_state_zip": taxpayer_info.get("city_state_zip"),
            "ssn_or_ein": taxpayer_info.get("tin"),
            "signature_date": datetime.now().strftime("%Y-%m-%d")
        }

        # Generate PDF
        filename = f"W9_{creator_id}.pdf"
        filepath = os.path.join(self.output_dir, filename)

        self._generate_w9_pdf(form_data, filepath)

        # Save to database
        tax_form = TaxForm(
            creator_id=creator_id,
            form_type=TaxFormTypeEnum.FORM_W9,
            tax_year=datetime.now().year,
            form_data=form_data,
            pdf_url=filepath,
            pdf_filename=filename
        )

        self.db.add(tax_form)
        self.db.commit()
        self.db.refresh(tax_form)

        return tax_form

    def _generate_w9_pdf(self, data: Dict, filepath: str):
        """Generate W-9 PDF."""
        c = canvas.Canvas(filepath, pagesize=letter)
        width, height = letter

        # Title
        c.setFont("Helvetica-Bold", 14)
        c.drawString(1*inch, height - 1*inch, "Form W-9")
        c.setFont("Helvetica", 10)
        c.drawString(1*inch, height - 1.3*inch, "Request for Taxpayer Identification Number and Certification")

        # Name
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1*inch, height - 2*inch, "1. Name:")
        c.setFont("Helvetica", 9)
        c.drawString(1*inch, height - 2.2*inch, data["name"])

        # Business name
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1*inch, height - 2.6*inch, "2. Business name (if different):")
        c.setFont("Helvetica", 9)
        c.drawString(1*inch, height - 2.8*inch, data.get("business_name", "N/A"))

        # Tax classification
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1*inch, height - 3.2*inch, "3. Federal tax classification:")
        c.setFont("Helvetica", 9)
        c.drawString(1*inch, height - 3.4*inch, data["tax_classification"])

        # Address
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1*inch, height - 3.8*inch, "5. Address:")
        c.setFont("Helvetica", 9)
        c.drawString(1*inch, height - 4*inch, data["address"])
        c.drawString(1*inch, height - 4.2*inch, data["city_state_zip"])

        # TIN
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1*inch, height - 4.6*inch, "Taxpayer Identification Number:")
        c.setFont("Helvetica", 9)
        c.drawString(1*inch, height - 4.8*inch, f"SSN or EIN: {data['ssn_or_ein']}")

        # Signature line
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1*inch, height - 5.5*inch, "Signature:")
        c.line(2*inch, height - 5.5*inch, 5*inch, height - 5.5*inch)
        c.setFont("Helvetica", 9)
        c.drawString(5.5*inch, height - 5.5*inch, f"Date: {data['signature_date']}")

        # Footer
        c.setFont("Helvetica", 8)
        c.drawString(1*inch, 0.5*inch, "Generated by CreatorSync Tax Optimizer")

        c.save()
